#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkpNZTWr3xXJbsHxtroAqA6DPkLEpEOewXOIBwMNiUhhuMPCGALcxrohx6qdprXdVfP7Ngxx4H1+se9MWpE7f7TihdHSxvu7Avgn/FyQNeob26VB3vsLhI1OLBJ6acwYaFaLKD74eXT2saWudqO1OS8SQ9SWL1d5gd9T0O0EDjjLJ8YRH2lM4aSu4dBWNXanBKhKLIsGdQYssHv3IJN0FWgvIVD9fykgnwP/VNgynUtlVDkp2JGuqNhgSawv2oditgKorM9ecQ6R2lkdOti7a4lGxxgW0ss96l+OSLpjrdIR5jZJZYQPFuonyYc4xwLVdy8Salm5Dw7ctWMROI5tNx random-name
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw==

ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
